### PR TITLE
add example

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
ping @John-Colvin

**Comment by John-Colvin** [comment]
Is it just me or is the auto-tester not checking this using the new `.travis.yml`?

**Comment by 9il** [comment]
Hmm... looks like #3 does not work.

**Comment by John-Colvin** [comment]
#3 does work, but it seems like travis wasn't doing a proper merge for the pull request and therefore wasn't seeing the new .travis.yml

Does travis just check the PR itself, not what it would be like when merged? That's not very good.

**Comment by 9il** [comment]
Yes, it works =). Looks like travis doing both. You can see 2 checks in a PR.

**Comment by John-Colvin** [comment]
Ah, so that's what that is. OK, no problems there.

**Pull request merged**
